apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-agentry-fe
  namespace: skala-practice   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk-agentry-fe
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 09bb72ef7dcb3ee947516afa1d43e3c2
      labels:
        app: sk-agentry-fe
    spec:
      serviceAccountName: default
      containers:
        - name: sk-agentry-fe
          image: amdp-registry.skala-ai.com/skala25a/sk059-sk-agentry-fe:2.0.0
          imagePullPolicy: Always
          env:
            - name: LOGGING_LEVEL
              value: DEBUG
            - name: USER_NAME
              value: skala
            - name: NAMESPACE
              value: skala-edu
