pipeline {
    agent any

    environment {
        GIT_URL = 'https://github.com/Team-GY/SK_Agentry_FE.git'
        GIT_BRANCH = 'main' // 또는 master
        GIT_ID = 'skala-github-hgy2124' // GitHub PAT credential ID
        IMAGE_REGISTRY = 'amdp-registry.skala-ai.com/skala25a'
        IMAGE_NAME = 'sk-agentry-fe'
        IMAGE_TAG = '1.0.0'
        DOCKER_CREDENTIAL_ID = 'skala-image-registry-hgy2124'  // Harbor 인증 정보 ID
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: "${GIT_BRANCH}",
                    url: "${GIT_URL}",
                    credentialsId: "${GIT_ID}"   // GitHub PAT credential ID
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('SK_Agentry_FE') {  
                    script {
                        withDockerRegistry([url: "https://${IMAGE_REGISTRY}", credentialsId: "${DOCKER_CREDENTIAL_ID}"]) {
                            sh """
                                docker build --platform=linux/amd64 -t ${IMAGE_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} .
                                docker push ${IMAGE_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
                            """
                        }
                    }
                }
            }
        }


        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                    kubectl apply -f ./k8s
                    kubectl rollout status deployment/sk059-my-app
                '''
            }
        }
    }
}

